import random
from palettes import id_palette

matched_sprites = {'Terra': {'name': 'TERRA', 's_id': 0, 'p_id': 0},
                   'Locke': {'name': 'LOCKE', 's_id': 1, 'p_id': 1},
                   'Cyan': {'name': 'CYAN', 's_id': 2, 'p_id': 2},
                   'Shadow': {'name': 'SHADOW', 's_id': 3, 'p_id': 3},
                   'Edgar': {'name': 'EDGAR', 's_id': 4, 'p_id': 4},
                   'Sabin': {'name': 'SABIN', 's_id': 5, 'p_id': 5},
                   'Celes': {'name': 'CELES', 's_id': 6, 'p_id': 6},
                   'Strago': {'name': 'STRAGO', 's_id': 7, 'p_id': 7},
                   'Relm': {'name': 'RELM', 's_id': 8, 'p_id': 8},
                   'Setzer': {'name': 'SETZER', 's_id': 9, 'p_id': 9},
                   'Mog': {'name': 'MOG', 's_id': 10, 'p_id': 10},
                   'Gau': {'name': 'GAU', 's_id': 11, 'p_id': 11},
                   'Gogo': {'name': 'GOGO', 's_id': 12, 'p_id': 12},
                   'Umaro': {'name': 'UMARO', 's_id': 13, 'p_id': 13},
                   'Imp': {'name': 'KAPPA', 's_id': 15, 'p_id': 14},
                   'General Leo': {'name': 'LEO', 's_id': 16, 'p_id': 15},
                   'Ghost': {'name': 'GHOST', 's_id': 20, 'p_id': 17},
                   'Bird-JamesWhite89-FF6': {'name': 'BIRD', 's_id': 36, 'p_id': 32},
                   'Bomb-JamesWhite89-FF6': {'name': 'BOMB', 's_id': 38, 'p_id': 33},
                   'Cecil (Dark Knight)-MetroidQuest-EC': {'name': 'CECIL', 's_id': 40, 'p_id': 35},
                   'Cecil (Paladin)-MetroidQuest-EC': {'name': 'CECIL', 's_id': 41, 'p_id': 37},
                   'Cirno-HoxNorf-Touhou': {'name': 'CIRNO', 's_id': 44, 'p_id': 40},
                   'Edea-CtrlxZ-FF8': {'name': 'EDEA', 's_id': 49, 'p_id': 100},
                   'Exdeath-CtrlxZ-FF5': {'name': 'EXDETH', 's_id': 56, 'p_id': 102},
                   'Frog-MetroidQuest-EC': {'name': 'FROG', 's_id': 62, 'p_id': 46},
                   'Gestahl-MetroidQuest-EC': {'name': 'GESTAL', 's_id': 71, 'p_id': 48},
                   'Iffy-HoxNorf-Neptunia': {'name': 'IFFY', 's_id': 74, 'p_id': 52},
                   'Kain-MetroidQuest-EC': {'name': 'KAIN', 's_id': 79, 'p_id': 54},
                   'Lenna (White Mage)-HoxNorf-FF5': {'name': 'LENNA', 's_id': 86, 'p_id': 58},
                   'Magus-MetroidQuest-EC': {'name': 'MAGUS', 's_id': 90, 'p_id': 59},
                   'Mog-JamesWhite89-FF6E': {'name': 'MOG', 's_id': 92, 'p_id': 60},
                   'Nepgear-HoxNorf-Neptunia': {'name': 'NPGEAR', 's_id': 94, 'p_id': 61},
                   'Neptune-HoxNorf-Neptunia': {'name': 'NEPTUN', 's_id': 96, 'p_id': 64},
                   'Relm-MetroidQuest-EC': {'name': 'RELM', 's_id': 105, 'p_id': 69},
                   'Robo-Badass-CT': {'name': 'ROBO', 's_id': 107, 'p_id': 71},
                   'Schala-HoxNorf-CT': {'name': 'SCHALA', 's_id': 115, 'p_id': 75},
                   'Shantotto-HoxNorf-FF11': {'name': 'SHANTO', 's_id': 118, 'p_id': 109},
                   'Soldier-LoneRedMage-FF4': {'name': 'SOLDIER', 's_id': 119, 'p_id': 76},
                   'Terra-MetroidQuest-EC': {'name': 'TERRA', 's_id': 125, 'p_id': 78},
                   'Uni-HoxNorf-Neptunia': {'name': 'UNI', 's_id': 130, 'p_id': 79},
                   'Kuja-HoxNorf-FF9': {'name': 'KUJA', 's_id': 138, 'p_id': 82},
                   'Reimu-HoxNorf-Touhou': {'name': 'REIMU', 's_id': 139, 'p_id': 83},
                   'Ram-HoxNorf-Neptunia': {'name': 'RAM', 's_id': 140, 'p_id': 84},
                   'Rom-HoxNorf-Neptunia': {'name': 'ROM', 's_id': 141, 'p_id': 85},
                   'Marisa-HoxNorf-Touhou': {'name': 'MARISA', 's_id': 145, 'p_id': 86},
                   'Rumia-HoxNorf-Touhou': {'name': 'RUMIA', 's_id': 147, 'p_id': 87},
                   'Papyrus-LoneRedMage-Undertale': {'name': 'PAPPY', 's_id': 146, 'p_id': 88},
                   'Sans-LoneRedMage-Undertale': {'name': 'SANS', 's_id': 148, 'p_id': 89},
                   'Toadette-HoxNorf-Mario': {'name': 'TOADET', 's_id': 149, 'p_id': 90},
                   'Talim-HoxNorf-SC4': {'name': 'TALIM', 's_id': 150, 'p_id': 91},
                   'Katt-ATinySpook-BOF2': {'name': 'KATT', 's_id': 151, 'p_id': 92},
                   'Tonberry King-CDude-FF': {'name': 'TKING', 's_id': 153, 'p_id': 93},
                   'PajaMog-CDude-FF': {'name': 'PJMOG', 's_id': 155, 'p_id': 95},
                   'GrimLocke-Taloswind-FF6': {'name': 'LOCKE', 's_id': 156, 'p_id': 96},
                   'Emperor-HoxNorf-FF2': {'name': 'EMPROR', 's_id': 157, 'p_id': 101},
                   'Chen-HoxNorf-Touhou': {'name': 'CHEN', 's_id': 158, 'p_id': 110},
                   'Sora-HoxNorf-KH': {'name': 'SORA', 's_id': 160, 'p_id': 112},
                   'Soldier': {'name': 'SOLDR', 's_id': 14, 'p_id': 18},
                   'Banon-Duncan': {'name': 'BANON', 's_id': 17, 'p_id': 16},
                   'Esper Terra': {'name': 'TERRA', 's_id': 18, 'p_id': 44},
                   'Merchant': {'name': 'MERCH', 's_id': 19, 'p_id': 14},
                   'Kefka': {'name': 'KEFKA', 's_id': 21, 'p_id': 56},
                   'Aerith-HoxNorf-FF7': {'name': 'AERITH', 's_id': 30, 'p_id': 97},
                   'Ayla-CrumpledMedal-CT': {'name': 'AYLA', 's_id': 31, 'p_id': 98},
                   'Baram-PocoLoco-FF6': {'name': 'BARAM', 's_id': 32, 'p_id': 14},
                   'Barret-CtrlxZ-FF7': {'name': 'BARRET', 's_id': 33, 'p_id': 14},
                   'Bartz-HoxNorf-FF5': {'name': 'BARTZ', 's_id': 34, 'p_id': 30},
                   'Berserker-Badass-FF5': {'name': 'ZERKER', 's_id': 35, 'p_id': 31},
                   'Boco-JamesWhite89-FF5': {'name': 'BOCO', 's_id': 37, 'p_id': 14},
                   'Bubble Dragon-Badass-BB': {'name': 'BUBBLE', 's_id': 39, 'p_id': 14},
                   'Chancellor-Zozma-FF6': {'name': 'CHNCLR', 's_id': 42, 'p_id': 14},
                   'Cid-HoxNorf-FF4': {'name': 'CID', 's_id': 43, 'p_id': 38},
                   'Cloud-HoxNorf-FF7': {'name': 'CLOUD', 's_id': 45, 'p_id': 14},
                   'Crono (No Sword)-Badass-CT': {'name': 'CRONO', 's_id': 46, 'p_id': 99},
                   'Crono (Sword)-Badass-CT': {'name': 'CRONO', 's_id': 47, 'p_id': 99},
                   'Devout-HoxNorf-FF': {'name': 'DEVOUT', 's_id': 48, 'p_id': 14},
                   'Edge-PocoLoco-FF4': {'name': 'EDGE', 's_id': 50, 'p_id': 41},
                   'Edward-SpoonyBard-FFRK': {'name': 'EDWARD', 's_id': 51, 'p_id': 43},
                   'Edward-Zozma-FF4': {'name': 'EDWARD', 's_id': 52, 'p_id': 42},
                   'Eiko-PocoLoco-FF9': {'name': 'EIKO', 's_id': 53, 'p_id': 14},
                   'Eiko-ScarabEnigma-FF9': {'name': 'EIKO', 's_id': 54, 'p_id': 14},
                   'Elarra-HoxNorf-FFRK': {'name': 'ELARRA', 's_id': 55, 'p_id': 14},
                   'Faris (Summoner)-FEOK-FF5': {'name': 'FARIS', 's_id': 57, 'p_id': 14},
                   'Faris-HoxNorf-FF5': {'name': 'FARIS', 's_id': 58, 'p_id': 14},
                   'Fish-ScarabEnigma-FF6': {'name': 'FISH', 's_id': 59, 'p_id': 45},
                   'Freya-HoxNorf-FF9': {'name': 'FREYA', 's_id': 60, 'p_id': 14},
                   'Frog-Badass-CT': {'name': 'FROG', 's_id': 61, 'p_id': 103},
                   'FuSoYa-FEOK-FF4': {'name': 'FUSOYA', 's_id': 63, 'p_id': 47},
                   'Galuf-HoxNorf-FF5': {'name': 'GALUF', 's_id': 64, 'p_id': 14},
                   'Gardevoir-LoneRedMage-Pokemon': {'name': 'GARDEV', 's_id': 65, 'p_id': 14},
                   'Garnet (Long Hair)-HoxNorf-FF9': {'name': 'GARNET', 's_id': 66, 'p_id': 14},
                   'Garnet (Short Hair)-HoxNorf-FF9': {'name': 'GARNET', 's_id': 67, 'p_id': 14},
                   'Gau (Suit)-Zozma-FF6': {'name': 'GAU', 's_id': 68, 'p_id': 11},
                   'General Leo (Full)-SpoonyBard-FF6': {'name': 'LEO', 's_id': 69, 'p_id': 15},
                   'General Leo (Redone)-SpoonyBard-FF6': {'name': 'LEO', 's_id': 70, 'p_id': 15},
                   'Gilgamesh-Kugawattan-FF5': {'name': 'GILGA', 's_id': 72, 'p_id': 104},
                   'Golbez-FEOK-FF4': {'name': 'GOLBEZ', 's_id': 73, 'p_id': 50},
                   'Impressario-LoneRedMage-FF6': {'name': 'IMPRES', 's_id': 75, 'p_id': 14},
                   'Interceptor-JamesWhite89-FF6': {'name': 'GUDBOI', 's_id': 76, 'p_id': 14},
                   'Iris-HoxNorf-FF15': {'name': 'IRIS', 's_id': 77, 'p_id': 14},
                   'Jessie-HoxNorf-FF7': {'name': 'JESSIE', 's_id': 78, 'p_id': 14},
                   'Kain-SpoonyBard-FFRK': {'name': 'KAIN', 's_id': 80, 'p_id': 55},
                   'Katarin-Zozma-FF6': {'name': 'KATRIN', 's_id': 81, 'p_id': 14},
                   'Kelgar-CtrlxZ-FF5': {'name': 'KELGAR', 's_id': 82, 'p_id': 14},
                   'King Baron-JamesWhite89-FF4': {'name': 'BARON', 's_id': 83, 'p_id': 14},
                   'Krile-HoxNorf-FF5': {'name': 'KRILE', 's_id': 84, 'p_id': 14},
                   'Laguna-PocoLoco-FF8': {'name': 'LAGUNA', 's_id': 85, 'p_id': 57},
                   'Lenna-HoxNorf-FF5': {'name': 'LENNA', 's_id': 87, 'p_id': 58},
                   'Lightning-FEOK-FF13': {'name': 'LIGHT', 's_id': 88, 'p_id': 14},
                   'Magus-FEOK-CT': {'name': 'MAGUS', 's_id': 89, 'p_id': 14},
                   'Mini-JamesWhite89-FF': {'name': 'MINI', 's_id': 91, 'p_id': 14},
                   'Mystic Knight-CtrlxZ-FF5': {'name': 'MYSTIC', 's_id': 93, 'p_id': 14},
                   'Neptune (Adult)-HoxNorf-Neptunia': {'name': 'NEPTUN', 's_id': 95, 'p_id': 63},
                   'Ninja-CtrlxZ-FF5': {'name': 'NINJA', 's_id': 97, 'p_id': 14},
                   'Onion Knight-FEOK-FF3': {'name': 'OK', 's_id': 98, 'p_id': 14},
                   'Palom-HoxNorf-FF4': {'name': 'PALOM', 's_id': 99, 'p_id': 66},
                   'Porom-HoxNorf-FF4': {'name': 'POROM', 's_id': 100, 'p_id': 67},
                   'Quina-SpoonyBard-FFRK': {'name': 'QUINA', 's_id': 101, 'p_id': 68},
                   'Quistis-FEOK-FF8': {'name': 'QUISTIS', 's_id': 102, 'p_id': 14},
                   'Rachel-Zozma-FF6': {'name': 'RACHEL', 's_id': 103, 'p_id': 14},
                   'Relm (Amano)-HoxNorf-FF6': {'name': 'RELM', 's_id': 104, 'p_id': 69},
                   'Reno-CtrlxZ-FF7': {'name': 'RENO', 's_id': 106, 'p_id': 70},
                   'Rosa-PocoLoco-FF4': {'name': 'ROSA', 's_id': 108, 'p_id': 72},
                   'Rydia (Child)-HoxNorf-FF4': {'name': 'RYDIA', 's_id': 109, 'p_id': 73},
                   'Rydia-HoxNorf-FF4': {'name': 'RYDIA', 's_id': 110, 'p_id': 74},
                   'Rydia-Zozma-FF4': {'name': 'RYDIA', 's_id': 111, 'p_id': 74},
                   'Ryu (Dragon)-Badass-BOF': {'name': 'RYU', 's_id': 112, 'p_id': 14},
                   'Ryu-Badass-BOF': {'name': 'RYU', 's_id': 113, 'p_id': 14},
                   'Samurai-CtrlxZ-FF5': {'name': 'SAMRAI', 's_id': 114, 'p_id': 14},
                   'Sephiroth-CtrlxZ-FF7': {'name': 'SEPH', 's_id': 116, 'p_id': 14},
                   'Seymour-LoneRedMage-FF10': {'name': 'SEYMOR', 's_id': 117, 'p_id': 105},
                   'Steiner-FEOK-FF9': {'name': 'STEINR', 's_id': 120, 'p_id': 14},
                   'Tellah-FEOK-FF4': {'name': 'TELLAH', 's_id': 121, 'p_id': 77},
                   'Terra (Amano Blond Cape)-JCollins-FF6': {'name': 'TERRA', 's_id': 122, 'p_id': 78},
                   'Terra (Amano Cape)-JCollins-FF6': {'name': 'TERRA', 's_id': 123, 'p_id': 0},
                   'Terra (Amano)-JCollins-FF6': {'name': 'TERRA', 's_id': 124, 'p_id': 0},
                   'Tiny Moogle-Rjenyawd-FF': {'name': 'MOOGLE', 's_id': 126, 'p_id': 10},
                   'Tohka-HoxNorf-DAL': {'name': 'TOHKA', 's_id': 127, 'p_id': 14},
                   'Tonberry-JamesWhite89-FF': {'name': 'TONBRY', 's_id': 128, 'p_id': 93},
                   'Ultros-PocoLoco-FF6': {'name': 'ULTROS', 's_id': 129, 'p_id': 14},
                   'Vanille-FEOK-FF13': {'name': 'VANILE', 's_id': 131, 'p_id': 14},
                   'Vivi-PocoLoco-FF9': {'name': 'VIVI', 's_id': 132, 'p_id': 14},
                   'White Mage-Matthew50-FF': {'name': 'WHM', 's_id': 133, 'p_id': 14},
                   'Yang-SApprentice-FF4': {'name': 'YANG', 's_id': 134, 'p_id': 80},
                   'Yuffie-HoxNorf-FF7': {'name': 'YUFFIE', 's_id': 135, 'p_id': 14},
                   'Zack-CtrlxZ-FF7': {'name': 'ZACK', 's_id': 136, 'p_id': 14},
                   'Zidane-HoxNorf-FF9': {'name': 'ZIDANE', 's_id': 137, 'p_id': 81},
                   'Umaro (Morph)-CDude-FF6': {'name': 'UMARO', 's_id': 142, 'p_id': 13},
                   'Sarisa-HoxNorf-FF5': {'name': 'SARISA', 's_id': 143, 'p_id': 14},
                   'Lilith-HoxNorf-Darkstalkers': {'name': 'LILITH', 's_id': 144, 'p_id': 14},
                   'Steve-PheonixMMKC777-Minecraft': {'name': 'STEVE', 's_id': 152, 'p_id': 14},
                   'Banjo Kazooie-HoxNorf-BK': {'name': 'BANJO', 's_id': 154, 'p_id': 94},
                   'Selphie-HoxNorf-FF8': {'name': 'SELPH', 's_id': 159, 'p_id': 111}
                   }


def paint():
    characters = random.sample(list(matched_sprites.items()), 20)
    f_names = []
    f_portraits = []
    f_sprites = []
    f_palettes = [str(x) for x in random.sample(list(id_palette.keys()), 7)]
    f_spalettes = [str(x) for x in random.choices(list(range(0, 6)), k=20)]
    for x in characters:
        f_names.append(x[1]['name'])
        f_portraits.append(str(x[1]['p_id']))
        f_sprites.append(str(x[1]['s_id']))
    return f" -name {'.'.join(f_names[:14])} -cpor {'.'.join(f_portraits[:14])}.{f_portraits[15]} -cspr" \
           f" {'.'.join(f_sprites)} -cpal {'.'.join(f_palettes)} -cspp {'.'.join(f_spalettes)}"

def palette():
    f_palettes = [str(x) for x in random.sample(list(id_palette.keys()), 7)]
    f_spalettes = [str(x) for x in random.choices(list(range(0, 6)), k=20)]
    return f" -cpal {'.'.join(f_palettes)} -cspp {'.'.join(f_spalettes)}"
