# Generated by Django 5.2.5 on 2025-09-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPreset',
            fields=[
                ('preset_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('featured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'featured_presets',
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('preset_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('creator_id', models.BigIntegerField()),
                ('creator_name', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
                ('flags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('arguments', models.TextField(blank=True, null=True)),
                ('official', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('gen_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'presets',
            },
        ),
        migrations.CreateModel(
            name='SeedLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_id', models.BigIntegerField()),
                ('creator_name', models.TextField()),
                ('seed_type', models.TextField()),
                ('share_url', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField()),
                ('server_name', models.TextField(blank=True, null=True)),
                ('server_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('random_sprites', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'seedlist',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bot_admin', models.IntegerField()),
                ('git_user', models.IntegerField()),
                ('race_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('preset', models.ForeignKey(db_column='preset_name', on_delete=django.db.models.deletion.CASCADE, to='webapp.preset')),
            ],
            options={
                'db_table': 'user_favorites',
                'unique_together': {('user_id', 'preset')},
            },
        ),
    ]
