# Generated by Django 5.2.5 on 2025-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=10),
        ),
    ]
