# Generated by Django 5.2.5 on 2025-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_preset_validation_error_preset_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='created_at_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedlog',
            name='timestamp_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
