# Generated by Django 5.2.5 on 2026-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_preset_validation_error_preset_validation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='preset',
            new_name='preset_name',
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='preset_name',
            field=models.CharField(db_column='preset_name', default='', max_length=255),
        ),
    ]
