# Generated by Django 5.2.5 on 2025-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_finalize_datetime_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedlog',
            name='args_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='seedlog',
            name='flagstring',
            field=models.TextField(blank=True, null=True),
        ),
    ]
