# Generated by Django 4.2.24 on 2025-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_seedlog_args_list_seedlog_flagstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preset',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
