# Generated by Django 6.0 on 2025-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_alter_preset_hidden_alter_preset_official"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlog",
            name="hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seedlog",
            name="seed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
