# Generated by Django 5.2.5 on 2026-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_userfavorite_unique_together_and_more'),
        ('webapp', '0010_apikey'),
    ]

    operations = [
    ]
