# Generated by Django 6.0.3 on 2026-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AddField(
            model_name="preset",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="presets", to="webapp.tag"
            ),
        ),
    ]
