# Generated by Django 5.2.5 on 2026-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_merge_20260525_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeedLog',
        ),
    ]
